# Generated by Django 3.2.25 on 2024-04-26 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPromotionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Promotion link')),
                ('image', models.ImageField(upload_to='banner', verbose_name='Promotion Picture')),
                ('index', models.SmallIntegerField(default=0, verbose_name='Display order')),
            ],
            options={
                'verbose_name': 'Homepage display promotion',
                'verbose_name_plural': 'Homepage display promotion',
                'db_table': 'df_index_promotion',
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Brand name')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brand',
                'db_table': 'df_brand',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Product category name')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product category',
                'db_table': 'df_product_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Product name')),
                ('ingredient', models.CharField(max_length=256, verbose_name='Product ingredient')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('image', models.ImageField(upload_to='product', verbose_name='Product picture')),
                ('stock', models.IntegerField(default=100, verbose_name='Product stock')),
                ('status', models.SmallIntegerField(choices=[(0, 'On stock'), (1, 'Out of stock')], default=0, verbose_name='Product state')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcategory', verbose_name='Product category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
                'db_table': 'df_product',
            },
        ),
        migrations.CreateModel(
            name='IndexProductBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='Picture')),
                ('index', models.SmallIntegerField(default=0, verbose_name='Display order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Homepage display product',
                'verbose_name_plural': 'Homepage display product',
                'db_table': 'df_index_banner',
            },
        ),
    ]
