# Generated by Django 3.2.25 on 2024-04-26 23:35

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('product', '0002_auto_20240426_2333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsCategory',
            new_name='ProductCategory',
        ),
    ]
