# Generated by Django 3.2.25 on 2024-04-26 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderInfo',
            fields=[
                ('order_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Order ID')),
                ('pay_method', models.SmallIntegerField(choices=[(1, 'Apple pay'), (2, 'Credit or debit card'), (3, 'Gift card'), (4, 'PayPal')], default=3, verbose_name='Payment method')),
                ('total_quantity', models.IntegerField(default=1, verbose_name='Total quantity')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('shipping_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Shipping fee')),
                ('order_status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Shipped'), (3, 'Delivered'), (4, 'Cancelled')], default=3, verbose_name='Order status')),
            ],
            options={
                'db_table': 'df_order_info',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('review', models.CharField(max_length=256, verbose_name='Review')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderinfo', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
            ],
            options={
                'db_table': 'df_order_product',
            },
        ),
    ]
